---
title: "Publications"
editor: visual
---

::: {.callout-note}
## Links

>- **Google Scholar**: <https://scholar.google.com/citations?hl=zh-CN&user=K3l1qnoAAAAJ>
>- **dblp**: <https://dblp.uni-trier.de/pid/19/3768-1.html>
:::

&emsp;

## 论文列表 

{{< include publications_by_year.md >}}




## 发明专利

1. **胡文斌**, 李坤.  
   百生来药物发现综合研发平台.  
   软件著作权：2023SR0648268，原始取得，全部权利，2023-03-25.

2. **胡文斌**, 陈沐坤 等.  
   面向多模态异构知识图谱的医疗综合应用平台.  
   软件著作权：2023SR0082071，原始取得，全部权利，2022-09-08.

3. **胡文斌**, 许平华 等.  
   湖北省医疗资源配置与调度平台.  
   软件著作权：2023SR0559605，原始取得，全部权利，2023-02-04.

4. **胡文斌**, 唐传慧, 过冰峰.  
   一种面向深度学习的网络个人信贷欺诈行为检测方法.  
   中国发明专利：CN201910434402.5，授权公告日：2021-05-04.

5. **胡文斌**, 王凯凯, 彭超, 梁欢乐, 刘开增.  
   一种基于语义社会网络本体分析技术的情境识别方法.  
   中国发明专利：ZL201310342234.X，授权公告日：2016-04-27.

6. **胡文斌**, 刘中舟, 许平华, 高旷, 陈沐坤.  
   一种动态基因调控网的网络演化分析方法及装置.  
   中国发明专利：ZL201811204292.5，授权公告日：2021-05-04.

7. **胡文斌**, 高旷.  
   一种基于网络高阶结构的社会网络免疫算法.  
   中国发明专利：CN201910432197.5，授权公告日：2019-05-23.

8. **胡文斌**, 王欢.  
   一种用于社会网络节点异常演化行为检测与评估方法.  
   中国发明专利：CN201711241949.0，授权公告日：2017-12-01.

9. **胡文斌**, 许珈铭.  
   一种中英文本实体关系抽取方法、系统及设备.  
   中国发明专利：CN202211316489.4，申请日：2023-02-03.

10. **胡文斌**, 俞文航.  
    一种用于化合物性质预测的图结构优化方法、系统和设备.  
    中国发明专利：CN202211284312.0，申请日：2023-02-03.

## 科研项目



- **基于孕期筛查大数据和人工智能的结构性出生缺陷早期诊断与干预研究**  
  国家科技部“十四五”国家重点研发计划（合作单位：复旦大学、南京医科大学、湖北省人民医院、深圳市人民医院等）

- **基于健康大数据的智能医疗服务算法与应用**  
  湖北省科技厅人工智能重大专项（合作单位：武汉大学人民医院、兰丁医疗等）

- **面向多模态异质知识图谱的医疗专家疾病诊断智能孪生体研究**  
  武汉市科技局人工智能创新专项（合作单位：科大讯飞武汉讯飞智能有限公司）

- **面向知识图谱补全与融合的中西医结合临床实践指南可操作性提升方法**  
  国家自然科学基金面上项目（合作单位：中南医院循证医学中心）

- **人工智能辅助表型药物发现关键技术研究**  
  广东省自然科学基金面上项目

- **联合企业获批国产化替代“揭榜挂帅”项目：面向生物医药企业的 PLM 平台研发**  
  企业联合攻关项目（国产化替代方向）

---

### 代表性省部级及以上纵向科研项目（部分）


| 项目名称 | 项目来源 | 执行周期 |
|---|---|---|
| 面向智能制造的生成式三维 CAD 科技创新团队 | 湖北省楚天英才计划科技创新团队项目 | 2024–2027 |
| 面向大模型训练的异构计算集群系统关键技术研究 | 湖北省科技创新计划重点研发项目 | 2024–2027 |
| 儿童用药品种及关键技术研发 | 国家科技重大专项子课题 | 2019–2021 |
| 基于大健康大数据的智能医疗服务算法与应用 | 湖北省科技厅人工智能重大专项 | 2019–2022 |
| 基于孕期筛查大数据和人工智能的结构性出生缺陷早期诊断与干预研究 | 国家科技部“十四五”国家重点研发计划 | 2024–2026 |
| 基于多模态数据因果推理的新型冠状病毒肺炎诊断算法与系统 | 国家自然科学基金委疫情专项 | 2021–2022 |
| 面向知识图谱补全与融合的中西医结合临床实践指南可操作性提升方法 | 国家自然科学基金面上项目 | 2021–2024 |
| 面向多模态异质知识图谱的医疗专家疾病诊断智能孪生体研究 | 武汉市科技局人工智能创新专项 | 2022–2024 |
| 迁移学习和主动学习一体化协同研究 | 国家自然科学基金青年基金项目 | 2021–2023 |
| 社会网络事件检测理论与预警方法研究 | 国家自然科学基金面上项目 | 2019–2023 |
| 基于智能物联网的多导联心电采集装置与智能监护平台 | 工信部揭榜项目 | 2022–2023 |
| 基于大语言模型的社交媒体用户中医药服务模式构建与应用研究 | 湖北省中医药联合基金重点项目 | 2025–2027 |
| 人工智能辅助表型药物发现关键技术研究 | 广东省自然科学基金 | 2025–2027 |
